logging:
    level:
        root: INFO
        org.springframework.security: INFO
        org.springframework.data.r2dbc: DEBUG

server:
    error:
        include-binding-errors: never
        include-message: always

security:
    jwt:
        secret: ThisIsAVerySecretSecret0123456789

spring:
    r2dbc:
        password: example
        url: r2dbc:postgresql://localhost/postgres
        username: postgres

springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        enabled: true

